### ISSUE TITLE
Messages related issues (in qa5) - 3

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#1764]
1.  I have a payload set here. Then I open Message Editor and Save it. Then the payload gets cleared.
![image](https://github.com/sartography/spiff-arena/assets/110527567/50a63b8a-53c6-476b-aee3-6bb5ae13ea69)

**Comment by madhurrya** [comment]
2. I created this model freshly today. But I am getting this warning message and even if I save it keeps coming.
https://qa5.spiffcrm.com/editor/process-models/misc:test:madhurya-testing:message-testing-5:message-end-event-1/files/message-end-event-1.bpmn

Please check this video.
https://drive.google.com/file/d/1ABlLBzMMyavFA9-XTKDY6TD3kQ43xVDx/view?usp=sharing

**Comment by madhurrya** [comment]
3. Even though I have added correlation properties to 'testMsg2' I can't add a matching condition
https://qa5.spiffcrm.com/editor/process-models/misc:test:madhurya-testing:message-testing-5:message-start-event-1/files/message-start-event-1.bpmn

![image](https://github.com/sartography/spiff-arena/assets/110527567/dfb54a40-94f1-4aea-98a0-10769494e84f)

**Comment by madhurrya** [comment]
4. Matching condition doesn't seem to work.
Here I have set the Matching condition as "Camri" But what I am sending is "Yaris". But it receives the message.
https://qa5.spiffcrm.com/i/83

![image](https://github.com/sartography/spiff-arena/assets/110527567/1e8f7daa-e761-4a61-a36a-2a75fd3007de)


![image](https://github.com/sartography/spiff-arena/assets/110527567/fd76f517-2d36-44bf-adae-84f7df6e420c)

**Comment by madhurrya** [comment]
5. Still noticing this 'This process is not waiting for' error

![image](https://github.com/sartography/spiff-arena/assets/110527567/0133b260-2b8a-4347-9a07-f11af0b397ff)

![image](https://github.com/sartography/spiff-arena/assets/110527567/fef27377-fe23-4ffb-a311-afc75f1cd1a3)

Models for that 
https://qa5.spiffcrm.com/process-models/misc:test:madhurya-testing:madhu-test-message-waiter
https://qa5.spiffcrm.com/process-models/misc:test:madhurya-testing:madhu-test-message-chef

**Comment by madhurrya** [comment]
6. In this model I changed the Correlation properties from Name to Age. Like this
https://qa5.spiffcrm.com/editor/process-models/misc:test:madhurya-testing:message-testing-5:send-message-2/files/send-message-2.bpmn
![image](https://github.com/sartography/spiff-arena/assets/110527567/2decd2af-c412-4bd3-bc15-925aa3d67e1b)

Now when I open this model which uses the same message it shows both the old one (Name) and new one (Age)

https://qa5.spiffcrm.com/editor/process-models/misc:test:madhurya-testing:message-testing-5:receive-message-2/files/receive-message-2.bpmn

**Comment by madhurrya** [comment]
7. When I Open message editor and save and close, the 'Variable name' get cleared. Similar to Issue no 1 above.
![image](https://github.com/sartography/spiff-arena/assets/110527567/e00b7c31-e029-4687-9089-0db144b0f4c9)

**Comment by madhurrya** [comment]
8. In existing process models, as soon as I click on a message related task/event, it shows the 'Unsaved changes.
Please save to avoid losing your work.' message

![image](https://github.com/sartography/spiff-arena/assets/110527567/cf0a9b49-4a68-48f8-b724-797b6b18214d)

![image](https://github.com/sartography/spiff-arena/assets/110527567/964afe07-0952-4681-905a-bd5f41493af7)

**Comment by madhurrya** [comment]
9. When I run this model it gives this error.
https://qa5.spiffcrm.com/process-models/misc:test:madhurya-testing:message-testing-5:send-message-3

![image](https://github.com/sartography/spiff-arena/assets/110527567/2ecf7bb9-c586-4864-998a-b25383067d63)

I think the reason is I have used apostrophe in correlation property name. We'll have to check/restrict special characters if they are causing issues

![image](https://github.com/sartography/spiff-arena/assets/110527567/6661c0a8-dc1f-4198-87ac-b1caed17fe29)

**Comment by theaubmov** [comment]
@madhurrya 1, 2, 3, 6, and 7 are fixed, for 8, this could occur with the old process on selected message elements. Some changes will be made, which will display an unsaved changes notification.

**Comment by madhurrya** [comment]
@theaubmov are these deployed to qa5? I guess not?

**Comment by burnettk** [comment]
they are now.

**Comment by madhurrya** [comment]
Issue 1 and 7 are fixed.

**Comment by madhurrya** [comment]
Issue 2, 3, 4, 5, 9 are still not fixed.

These are the models I used for testing today

https://dev.app.spiff.status.im/process-models/misc:qa:bpmn-model-testing:unit-test-receive-task-new
https://dev.app.spiff.status.im/process-models/misc:qa:bpmn-model-testing:unit-test-send-task-new
https://dev.app.spiff.status.im/process-models/misc:qa:bpmn-model-testing:unit-test-message-start-event
https://dev.app.spiff.status.im/process-models/misc:qa:bpmn-model-testing:unit-test-message-end-event

**Comment by madhurrya** [comment]
New issues related to messages will be added here https://github.com/sartography/spiff-arena/issues/1800

**Comment by theaubmov** [comment]
@madhurrya I think the main reason for issues related to correlation properties (2, 3, 4, and 5) is that they occur when you add a correlation property with a value that includes spaces, like this: <bpmn:correlationProperty id="Capital City" name="Capital City">. This causes issues in the editor because the standard in editor is that all element ids should not include spaces. To fix this, we can add validators to the message popup.

**Comment by madhurrya** [comment]
@theaubmov ah OK. I'll test without spaces tomorrow.
If that's the case we'll have to show a message to the user saying so. 
Because for the message name we show a message saying 'The mesage name should contain no spaces or special characters' 
But for Correlation properties no such message is shown.
Anyway it'll be good to add a validator for all these fields as special characters are also causing issues (No 9)

**Comment by madhurrya** [comment]
@theaubmov But shouldn't it be only for Ids that we should restrict those?
For example in process name we can add spaces, only for the Id it's restricted.
![image](https://github.com/sartography/spiff-arena/assets/110527567/6f6b6a09-7942-444f-a69b-41a55d14c5c6)

**Comment by theaubmov** [comment]
Yes 100%, Normally, the name field accepts values with spaces, but the property name of the correlation property in the editor is persisted and represents the correlationProperty ID and not the name.
![image](https://github.com/sartography/spiff-arena/assets/44379029/296ec9a1-b645-4ba8-afbf-3eb1dd430adb)
