### ISSUE TITLE
PI Migration - Timer update migration error

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#1909]
I updated the values of this Boundary cycle timer and tried to migrate the instance. It gave this error.

Model : https://timetracking.spiffworkflow.org/process-models/misc:qa:madhu-testing:boundary-cycle-timer
I changed "R/PT5M" to "R3/PT1M"

![Image](https://github.com/user-attachments/assets/a256ebd4-9022-4376-8024-1b67c1bc4b28)

**Comment by jasquat** [comment]
Note: the timer has to run at least once for this error to occur.

Looks like the error happens in:
```
SpiffWorkflow/task.py", line 177, in reset_branch
    self.data = deepcopy(self.parent.data) if data is None else data
```

The parent is None somehow.

@essweine any ideas what could be causing this? Should migrations even be allowed after the timer has gone off once?

**Comment by burnettk** [comment]
addressed by https://github.com/sartography/spiff-arena/pull/1918

**Comment by madhurrya** [comment]
Not sure whether this fix is deployed to timetracker, I am still getting that error.
![image](https://github.com/user-attachments/assets/a4fe354a-75e0-452b-b7e8-65121d16617d)

**Comment by jasquat** [comment]
It looks like this fix wasn't deployed out to any environment.

Running locally I do get the following error though. This happens when attempting to actually run the migration. The check code does seem to allow it to proceed now:
```
 File "/home/jason/projects/github/sartography/spiff-arena/spiffworkflow-backend/src/spiffworkflow_backend/services/workflow_execution_service.py", line 165, in spiff_run
    spiff_task.run()
  File "/home/jason/.cache/pypoetry/virtualenvs/spiffworkflow-backend-Z2xYSxWs-py3.12/lib/python3.12/site-packages/SpiffWorkflow/task.py", line 360, in run
    self.complete()
  File "/home/jason/.cache/pypoetry/virtualenvs/spiffworkflow-backend-Z2xYSxWs-py3.12/lib/python3.12/site-packages/SpiffWorkflow/task.py", line 376, in complete
    self.task_spec._on_complete(self)
  File "/home/jason/.cache/pypoetry/virtualenvs/spiffworkflow-backend-Z2xYSxWs-py3.12/lib/python3.12/site-packages/SpiffWorkflow/specs/base.py", line 368, in _on_complete
    child.task_spec._update(child)
  File "/home/jason/.cache/pypoetry/virtualenvs/spiffworkflow-backend-Z2xYSxWs-py3.12/lib/python3.12/site-packages/SpiffWorkflow/specs/base.py", line 260, in _update
    if self._update_hook(my_task):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jason/.cache/pypoetry/virtualenvs/spiffworkflow-backend-Z2xYSxWs-py3.12/lib/python3.12/site-packages/SpiffWorkflow/bpmn/specs/mixins/unstructured_join.py", line 36, in _update_hook
    task.cancel()
  File "/home/jason/.cache/pypoetry/virtualenvs/spiffworkflow-backend-Z2xYSxWs-py3.12/lib/python3.12/site-packages/SpiffWorkflow/task.py", line 370, in cancel
    self._drop_children()
  File "/home/jason/.cache/pypoetry/virtualenvs/spiffworkflow-backend-Z2xYSxWs-py3.12/lib/python3.12/site-packages/SpiffWorkflow/task.py", line 285, in _drop_children
    if force or child.has_state(TaskState.NOT_FINISHED_MASK):
                ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'has_state'
```

@essweine any thoughts?

**Comment by madhurrya** [comment]
@jasquat not sure whether the above fix got deployed or not. I just tried again and this time didn't get the error in migration. But got this error when it tried to run the cycle next time.

https://sample.spiffcrm.com/i/18

![image](https://github.com/user-attachments/assets/03008622-cac5-410d-92b4-93a268b03066)

**Comment by jasquat** [comment]
@madhurrya this is not fixed yet. We're still looking into what is causing it. I'm pretty sure it's due to the backend not removing the tasks that spiff has removed and they become out of sync.

**Comment by madhurrya** [comment]
In this instance I had a one cycle completed the milestones looked like this. - https://sample.spiffcrm.com/i/1031
![image](https://github.com/user-attachments/assets/1fe02501-a7ec-4e24-b6a7-b690b58492b4)

Then I changed the cycle timer values and migrated it. Then in the Milestones tab I see only the first 2 entries. The last 2 are missing. Is that the expected behaviour?
![image](https://github.com/user-attachments/assets/e316052c-1469-4a31-b58e-7be8ba9dfbc2)

Same happened with the Boundary cycle timer migration also.

**Comment by jasquat** [comment]
Oh, the events are not getting deleted however the tasks are. If you notice there are several `task_completed` events still in the table. Those are the missing events. Their tasks were deleted from the database so the task information cannot be pulled up for the events since the task information comes from the actual tasks.

We could cache the task information on the event so if the task goes away, the info persists or we could delete the events which feels really wrong.

In any case, this is a separate issue that isn't really related to process instance migrations since it should also be affecting reset.

**Comment by madhurrya** [comment]
@jasquat I didn't fully understand what you have explained above. What do you mean by tasks are deleted?
If you think this is a separate issue could you please create an issue for that, as I am not very clear to add that issue.

**Comment by jasquat** [comment]
Sure. #1941
