### ISSUE TITLE
Spiff bounties process

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#979]

**Comment by calexh-sar** [comment]
@harmeet-status does this process model fall under one of the current Status process groups?  If so, which one?  If not, where should it be placed?

**Comment by calexh-sar** [comment]
@harmeet-status is this what you had in mind:


![Image](https://github.com/sartography/spiff-arena/assets/54854669/db524148-b6b5-4f81-a215-05b41219148c)

**Comment by calexh-sar** [comment]
@harmeet-status couple of questions:

1. How do we validate that "Payment address is an ETH wallet"?
2. Which bounty hunter fields are considered PII

**Comment by harmeet-status** [comment]
> [@harmeet-status](https://github.com/harmeet-status) couple of questions:
> 
> 1. How do we validate that "Payment address is an ETH wallet"?
> 2. Which bounty hunter fields are considered PII?

1. https://docs.web3js.org/api/web3-validator/function/isAddress
2. Physical address, Payment address, Percentage split of bounty, per user

**Comment by harmeet-status** [comment]
Yes that is a good idea to save dev time.

**Comment by harmeet-status** [comment]
What is remaining on this ticket?

**Comment by calexh-sar** [comment]
@harmeet-status remaining work ifor the submission process ncludes:
- Move initial User Task to Start Event
- Add acceptance and rejection Discord messages
- Finalize Complete Bounty Request User Task
- Finalize Review Bounty Request User Task
- General clean-up
- Anything that comes up during QA testing

**Comment by calexh-sar** [comment]
@madhurrya and @dinithihj here are some notes on the flow and high level requirements for this issue.  Please let me know if you have and questions or need clarification.  I have a few test issues labeled as described below.

- URL to start process: https://dev.app.spiff.status.im/public/manage-productsprojects:develop-products-and-services:spiffworkflow-development:bounty_submission_start
- GitHub handle must be valid
  - Requestor is sent a Discord message if invalid
- Guest link and OTP sent to requestor via Discord
- Requested issue validation rules found in `validate-issue-request` DMN table
  - Requested issue must be have a `Bounty-claim` or `Bounty-compete` label
    - `Bounty-claim` issues can only have one assignee
    - `Bounty-compete` issues can have multiple assignees
  - If requested issue is not valid, requestor has chance to submit another issue
- Requestor provide required information
- Reviewer approves or rejects request based on provided information
  - This includes the requested issue, requestor info and any other issues the requestor had been assigned to previously.
  - Requestor notified of review outcome
  - If approved
    - Requestor assigned to issue
    - if issue status is `Backlog`, status changed to `In Progress`

**Comment by dinithihj** [comment]
@calexh-sar I will add all the issues I find during testing on this ticket.

1. When entering an incorrect GitHub handle process instance got to error status with the below error message 
https://dev.app.spiff.status.im/i/2127
![image](https://github.com/sartography/spiff-arena/assets/123297840/5bc70bd0-3b1e-4484-87c1-e6c31ab316d2)

**Comment by dinithihj** [comment]
2. When entering an incorrect discord username process instance got to error status with the below error message
https://dev.app.spiff.status.im/i/2130

![image](https://github.com/sartography/spiff-arena/assets/123297840/681cf06f-84fc-4c4b-99ad-01288372b0f7)

**Comment by dinithihj** [comment]
4. I typed in an issue number that doesn't have a label assigned. When I opened the Discord URL and entered "OPT", it displayed "Issue is not a bounty issue" as expected. But when I clicked the "Submit" button, the form only displayed the text "Thank you". I think the guest option isn't enabled for the "Resubmit Issue" user task.

![image](https://github.com/sartography/spiff-arena/assets/123297840/af35296f-5797-4319-805c-792d0541f926)

![image](https://github.com/sartography/spiff-arena/assets/123297840/094c8473-f397-4e6d-a51c-73c3788deadb)

**Comment by dinithihj** [comment]
5. If I leave the "City/State/Country" field empty, fill in the other details, and click the submit button, there's no validation for "City/State/Country" and I get the below error. https://dev.app.spiff.status.im/i/2144

But if I type something in "City/State/Country," then clear it, and click the submit button, a validation message shows up as expected.

Video link - https://drive.google.com/file/d/1sAcXe6gmoTtm_jtPR8CDyEDFQXwQ0qTF/view?usp=sharing

![image](https://github.com/sartography/spiff-arena/assets/123297840/96be7c41-de3f-469e-bc52-8e62781e281b)

**Comment by dinithihj** [comment]
6. I submitted a bounty request, and support approved it. Then, I created another bounty request for the same issue number. When I opened the Discord URL and entered "OPT," it correctly displayed "You are already assigned to this issue." But when I clicked the "Submit" button, the form that appeared was not properly formatted for resubmission.
https://dev.app.spiff.status.im/i/2146

![image](https://github.com/sartography/spiff-arena/assets/123297840/67c9a78c-a863-44ff-a8f9-c2f84bcc18a7)

**Comment by dinithihj** [comment]
7. When the support group member opens the "Review bounty process" task, an extra full stop (.) is displayed with the text proposal.

![image](https://github.com/sartography/spiff-arena/assets/123297840/f765134c-d63a-498e-9e9b-d9bf34811f5f)

**Comment by dinithihj** [comment]
8. Suggestion. When the support group member accepts or rejects the bounty request, the requestor gets below messages on the discord.

- Your request to work on this bounty issues has been accepted
- Your request to work on this bounty issues has been rejected

I think it would be good to include the issue number in the message, especially in the rejection message in case the user has submitted multiple requests.
And it should be in singular form - "issue" instead of "issues"

**Comment by dinithihj** [comment]
9. When the user submits the request, a Thank You page is displayed. On that page, can we use "URL" in capital letters everywhere to be consistent?

![image](https://github.com/sartography/spiff-arena/assets/123297840/888e2400-ab74-41ae-9ba3-dc027b6777af)

**Comment by dinithihj** [comment]
10. Spelling mistake - "Spacify" in bounty submission form

![image](https://github.com/sartography/spiff-arena/assets/123297840/a9517d63-6b0d-4bfd-887a-414ca1ac02ce)

**Comment by dinithihj** [comment]
11. When the process instance is in the "Enter OPT" stage and I open it as an admin, the process instance page shows the message "This next task is assigned to a different person or team. There is no action for you to take at this time."

But when the process instance is in the "Complete Bounty Request" stage and I open it as an admin, the page shows the message "This next task is assigned to user(s): , . There is no action for you to take at this time."

The assignee should either be shown here, or it should display, "This next task is assigned to a different person or team." The current message is confusing.
https://dev.app.spiff.status.im/i/2437

![image](https://github.com/sartography/spiff-arena/assets/123297840/1f584ba1-4c93-4f3f-b629-e1336ac0c3a0)
![image](https://github.com/sartography/spiff-arena/assets/123297840/6b86e484-90ce-4b38-9e7e-50641718254f)

**Comment by dinithihj** [comment]
12. OPT is not validated correctly. I entered 1234 as the OPT, and it let me proceed to the next step.
https://dev.app.spiff.status.im/i/2451

**Comment by calexh-sar** [comment]
@dinithihj pls retest #3.

**Comment by calexh-sar** [comment]
@burnettk and/or @jasquat assuming I am correct that #11  above is a backend issue, would you please review and provide your thoughts on whether this should become a new issue or left as is.

**Comment by burnettk** [comment]
@calexh-sar yes, thank you, a new issue would be excellent. i will file. we think we can sort this out in short order, but probably better not to entangle it with bounty any more than necessary, since it's more of a "guest task issue."

**Comment by dinithihj** [comment]
13. When I enter an incorrect issue number (one that doesn't exist) and open the Discord URL and enter "OPT," it correctly displays the message "Invalid issue number." It also says "Click Submit to submit another issue or Cancel to cancel this request." However, there's no "Cancel" button displayed to cancel the request.

![image](https://github.com/sartography/spiff-arena/assets/123297840/2af607e2-29fc-4055-8cbf-e33be7d342f5)

**Comment by dinithihj** [comment]
14. (Similar to 4.) When I enter an incorrect issue number (one that doesn't exist) and open the Discord URL and enter "OPT," it correctly displays the message "Invalid issue number." It also says "Click Submit to submit another issue or Cancel to cancel this request." When I click the Submit button, it doesn't show me an interface to resubmit the request. It just displays "Thank You."

![image](https://github.com/sartography/spiff-arena/assets/123297840/ca4f7108-7cfd-4bf8-95e3-e37a7776a978)

**Comment by dinithihj** [comment]
> @dinithihj pls retest #3, #6, #7, #9, #10. and #12.
> 
> For $5, "city_state_country" is now a required field (should have been all along).
> 
> Regarding #8, @harmeet-status will be providing the text for the Discord messages.

@calexh-sar 3. 5. 7. 9. 10. 12. are fixed now. I have crossed them off

Regarding 6. - The unformatted form is not displaying now, but it should show an interface to resubmit the request, correct?

**Comment by dinithihj** [comment]
15. User A creates a bounty submission for issue 111, which is labeled as a bounty-claim. Before the support user approves it, user B also creates a bounty submission for the same issue 111. Now, when the support user logs in, he sees two process instances: one from user A and one from user B. If the support user accepts both requests, issue 111 is assigned to both user A and user B. This is incorrect because the bounty-claim issue can only be assigned to one user.

There should be a validation step to check the current state of the issue during the support user review process.

**Comment by dinithihj** [comment]
16. When a user creates a bounty submission for a bounty-compete issue, shouldn't we display the information mentioned in https://www.notion.so/Spiff-Bounties-22a7e2e23ee843c7bffd261ab15d1c9b -  Page 3.5 - Existing devs working on this? If this has already been discussed and agreed, please ignore this.

**Comment by dinithihj** [comment]
17. The process model document says that the bounty application should allow uploading files for the proposal, which is currently not supported. If this has already been discussed and agreed, please ignore this.

![image](https://github.com/sartography/spiff-arena/assets/123297840/fa649a2a-eba0-43d3-9ca7-adbdab741f23)

**Comment by calexh-sar** [comment]
@dinithihj - in response to `Regarding 6. - The unformatted form is not displaying now, but it should show an interface to resubmit the request, correct?`: Yes, once the Signal button issue is addressed you should be able to see and test that form.  It is displaying in the form builder if you want to see what should be displaying for any reason.

**Comment by harmeet-status** [comment]
> Regarding https://github.com/sartography/spiff-arena/pull/15, good catch. I think that should be considered as out-of-scope for the current iteration, but could be considered as a future update. We should wait to see how @harmeet-status would like to proceed with this suggestion.

This is edge case, so let's leave for now and fix later.

**Comment by harmeet-status** [comment]
Bugs found:

1. Duplicate help text 
![Image](https://github.com/sartography/spiff-arena/assets/104047049/ac8a2081-4151-4888-9d32-7ea41b794859)

**Comment by calexh-sar** [comment]
@dinithihj I am seeing the duplicate help text @harmeet-status identified above in both FireFox and Chrome, but not in the Form Builder:

![Image](https://github.com/sartography/spiff-arena/assets/54854669/d1589c0f-36dd-481d-a419-8828bf056345)

Would you please see if you can replicate this in a test process and if so, write an issue so we can address it.

**Comment by calexh-sar** [comment]
@harmeet-status regarding the effort required for #17, I would estimate 0.25-0.5 DD.  The other reason I suggest that we not add this at  this time is due to the flux on how we are handling file uploads.

**Comment by calexh-sar** [comment]
@dinithihj would you please create a test process which has a Guest Human Task and confirm if the use of Signal buttons is not working in MUI.  If so, please write a new issue for this.

**Comment by harmeet-status** [comment]
> @harmeet-status regarding the effort required for #17, I would estimate 0.25-0.5 DD. The other reason I suggest that we not add this at this time is due to the flux on how we are handling file uploads.

Let's leave this out for now then.

**Comment by harmeet-status** [comment]
> @harmeet-status regarding the effort required for #17, I would estimate 0.25-0.5 DD. The other reason I suggest that we not add this at this time is due to the flux on how we are handling file uploads.

Let's leave this out for now. Another thing I'm worried about is people uploading viruses...

**Comment by harmeet-status** [comment]
@calexh-sar I couldn't find where to change the confirmation page text on the guest task:

**ORIGINAL**
Title: Thanks
Description: Please check Discord for further instructions. You should receive two messages, one with a Guest URL and another with a One-Time-Password.

If you did not receive a Guest URL and One-Time-Password, your GitHub handle is either not valid or you have not requested to be a Collaborator Contributor on the repository.
Or if you did not receive any Discord messages, your Discord username is invalid.
In both of these cases, your request was cancelled and you will need to resubmit. Please make sure your GitHub credentials and Discord username are correct.


**NEW**
Title: Please check Discord for further instructions
Description: You will have received a link using

**Comment by harmeet-status** [comment]
@calexh-sar how can we handle these edge case scenarios?

> If you did not receive a Guest URL and One-Time-Password, your GitHub handle is either not valid or you have not requested to be a Collaborator Contributor on the repository.

Or if you did not receive any Discord messages, your Discord username is invalid.`

**Comment by calexh-sar** [comment]
> [@calexh-sar](https://github.com/calexh-sar) how can we handle these edge case scenarios?
> 
> > If you did not receive a Guest URL and One-Time-Password, your GitHub handle is either not valid or you have not requested to be a Collaborator Contributor on the repository.
> 
> > Or if you did not receive any Discord messages, your Discord username is invalid.`

@harmeet-status the initial instructions presented should be clear that the bounty hunter needs to be a collaborator in the repository the issue they are requesting resides.  As for incorrect GitHub handle and/or Discord username, they just need to provide the correct one.

**Comment by dinithihj** [comment]
> @dinithihj would you please create a test process which has a Guest Human Task and confirm if the use of Signal buttons is not working in MUI. If so, please write a new issue for this.

@calexh-sar Created a new ticket - https://github.com/sartography/spiff-arena/issues/1727

**Comment by madhurrya** [comment]
18. When the user is not in the repo, it sends this message to ' Not valid assignee'. Might be better to explain this further

19. For this, it might be better to explain how he can request to add him to the repo.
![image](https://github.com/sartography/spiff-arena/assets/110527567/4faa8eb5-8004-4910-aef4-f182b05f51bc)

20. Spelling
![image](https://github.com/sartography/spiff-arena/assets/110527567/e27a0440-4398-41b2-86db-2f9c071074e1)

21. Grammar
![image](https://github.com/sartography/spiff-arena/assets/110527567/55328cbc-f1a6-40e0-b5ec-b8aafde13e55)

22. Is it better to show these 2 in one line?
![image](https://github.com/sartography/spiff-arena/assets/110527567/1443a46a-5715-4689-948f-8016c7cd298b)

**Comment by madhurrya** [comment]
24. Got this error when resubmitting
https://dev.app.spiff.status.im/i/76
![image](https://github.com/sartography/spiff-arena/assets/110527567/40591161-b522-4fb1-bddf-e2bb617f864f)

**Comment by madhurrya** [comment]
25. When I click the Home button here it shows the Spiff home page for few seconds and then it says Access denied. Please check this videos. https://drive.google.com/file/d/19Oq9wqR4TXJxYwR99gv6RnFtDX7x6zQl/view?usp=sharing

![image](https://github.com/sartography/spiff-arena/assets/110527567/a593ec27-c66f-4073-9278-f9416b0bc375)

**Comment by madhurrya** [comment]
26. @calexh-sar @harmeet-status are you doing any updates in the model at the moment? I am getting the same above error now when submitting a request also https://dev.app.spiff.status.im/i/85

**Comment by madhurrya** [comment]
27. @harmeet-status is there any security risk in sending both the url and the password at the same time to the same place?
![image](https://github.com/sartography/spiff-arena/assets/110527567/9a26643d-b7a8-4df3-a6fb-c9b69da9a39c)

**Comment by harmeet-status** [comment]
> 27. [@harmeet-status](https://github.com/harmeet-status) is there any security risk in sending both the url and the password at the same time to the same place?
>     ![image](https://private-user-images.githubusercontent.com/110527567/339333372-9a26643d-b7a8-4df3-a6fb-c9b69da9a39c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNzg3NzcsIm5iZiI6MTcxODI3ODQ3NywicGF0aCI6Ii8xMTA1Mjc1NjcvMzM5MzMzMzcyLTlhMjY2NDNkLWI3YTgtNGRmMy1hNmZiLWM5YjY5ZGE5YTM5Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QxMTM0MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NzViNmNmOWJiMmNlY2NjMjRmOGEyYzBlMWI5MjE5ZmJhYjcxNDliZjBiZWExNTg5OWY1MWY3MGFlZTRjZTVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1VrscMrAK3i1OLx5SaoddR55KUF053NMJwCBUV_Kx48)

This is ok, run past security. I'm actually considering just sending 1 message, with the secret in the URL. All websites when they get you to confirm the email belongs to you, send you just 1 link to verify. We can follow the same practise, since we no longer allow the user to retrieve an already filled out request, the need to have 2 separate messages, 1 including the link and the other including the password is no longer required.

@calexh-sar could you pls update the model to just use the GUID and not required a password

**Comment by calexh-sar** [comment]
> > > [@calexh-sar](https://github.com/calexh-sar) how can we handle these edge case scenarios?
> > > > If you did not receive a Guest URL and One-Time-Password, your GitHub handle is either not valid or you have not requested to be a Collaborator Contributor on the repository.
> > > 
> > > 
> > > > Or if you did not receive any Discord messages, your Discord username is invalid.`
> > 
> > 
> > [@harmeet-status](https://github.com/harmeet-status) the initial instructions presented should be clear that the bounty hunter needs to be a collaborator in the repository the issue they are requesting resides. As for incorrect GitHub handle and/or Discord username, they just need to provide the correct one.
> 
> Is there way to check if the user is a current collaborator through the API?

@harmeet-status we are using the GitHub REST API to check if the requestr is a current collaborator.

**Comment by calexh-sar** [comment]
> 27. [@harmeet-status](https://github.com/harmeet-status) is there any security risk in sending both the url and the password at the same time to the same place?
>     ![image](https://private-user-images.githubusercontent.com/110527567/339333372-9a26643d-b7a8-4df3-a6fb-c9b69da9a39c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyODE4MzIsIm5iZiI6MTcxODI4MTUzMiwicGF0aCI6Ii8xMTA1Mjc1NjcvMzM5MzMzMzcyLTlhMjY2NDNkLWI3YTgtNGRmMy1hNmZiLWM5YjY5ZGE5YTM5Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QxMjI1MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMzdiY2MwNjBkNGVlOWQwZDZiMTE1ZjBlMzBlYjAzMmFkZjkwZDgxMWZhNTY1YjczMGJhZWUxNDhkNTNmZWRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._RCL1m1tOqFNRL-PEfmWs-rRodZC-zz5331vU6uhJDg)

I am following what I understand is the process @MarD0607 established with Status Security Team approval that is is acceptable to send both to the same place, but they are in two different Discord messages.  If you hover over each, you can determine that each is a separate message.  The time very well may be the same since they were sent sequentially, but they are distinct.

**Comment by calexh-sar** [comment]
> 23. When I submit/resubmit it shows this loading screen for a long time. It might be better to show some text here. Otherwise user might feel something is wrong.
>     ![image](https://private-user-images.githubusercontent.com/110527567/339330300-f79f3223-39de-4d16-b047-cda0a9fe3269.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyODg5NDksIm5iZiI6MTcxODI4ODY0OSwicGF0aCI6Ii8xMTA1Mjc1NjcvMzM5MzMwMzAwLWY3OWYzMjIzLTM5ZGUtNGQxNi1iMDQ3LWNkYTBhOWZlMzI2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QxNDI0MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Y2VmNmY5NWNjZTg5MTU0ZmMwZmI4ZjM5Y2Q3MGMyOWUwN2VmYjY0ZmVkMGRmYTRmN2UyYzEwYWYwYmZjMTg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wDzvPHc3iqCoCvgZ9pgiTnf70UOBmAsxcktbTgykRq4)

@madhurrya or @dinithihj I added some text to display after the initial submission and it is not showing up.  I suspect that this feature is not working on the interstitial page when transitioning between Guest User Forms, but not sure.  If you haven't already, would you please set up a test process to confirm/refute that this is the issue and if it is, write up an issue for it.

**Comment by calexh-sar** [comment]
> 24. Got this error when resubmitting
>     https://dev.app.spiff.status.im/i/76
>     ![image](https://private-user-images.githubusercontent.com/110527567/339330796-40591161-b522-4fb1-bddf-e2bb617f864f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyODg5NDksIm5iZiI6MTcxODI4ODY0OSwicGF0aCI6Ii8xMTA1Mjc1NjcvMzM5MzMwNzk2LTQwNTkxMTYxLWI1MjItNGZiMS1iZGRmLWUyYmI2MTdmODY0Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QxNDI0MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZWViNjg3YWQ3ZjMzMGViYWNjOGZkY2I4N2Q4MDc3ODAyODFmYWY1YzUxZTYzYjc4MzRjNTc0NDAwOGRkZGVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9TnwnXg8C4G97t9bbqRJb_xt2rp2QltTwE00n-xBxnI)

I am not getting this error.  Pls retest and if still getting the error, provide more detail on the steps to reproduce.

**Comment by calexh-sar** [comment]
> 25. When I click the Home button here it shows the Spiff home page for few seconds and then it says Access denied. Please check this videos. https://drive.google.com/file/d/19Oq9wqR4TXJxYwR99gv6RnFtDX7x6zQl/view?usp=sharing
> 
> ![image](https://private-user-images.githubusercontent.com/110527567/339331561-a593ec27-c66f-4073-9278-f9416b0bc375.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyODg5NDksIm5iZiI6MTcxODI4ODY0OSwicGF0aCI6Ii8xMTA1Mjc1NjcvMzM5MzMxNTYxLWE1OTNlYzI3LWM2NmYtNDA3My05Mjc4LWY5NDE2YjBiYzM3NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QxNDI0MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NGRjOWVkNTVlZmM3YjUwMmNkMTFjOWNhMGMxODgzMTUyMzBhM2EzNzc0ZTg4MjlkNWEyYTVmYjg5NGJjYjc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CrAqMdVVSZjButiHbM-z7fIV6ga4wraitcJ8jj48iIo)

@madhurrya I suspect this issue here is we shouldn't take a Guest user to the Home page since they don't have the rights to do anything there.  If @burnettk and/or @jasquat concur, please write up an issue so we can address this.

**Comment by calexh-sar** [comment]
@harmeet-status unless you indicate otherwise, I will assume you will be addressing the text related issues 18-22 above.

**Comment by madhurrya** [comment]
> > 24. Got this error when resubmitting
> >     https://dev.app.spiff.status.im/i/76
> >     ![image](https://private-user-images.githubusercontent.com/110527567/339330796-40591161-b522-4fb1-bddf-e2bb617f864f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyODg5NDksIm5iZiI6MTcxODI4ODY0OSwicGF0aCI6Ii8xMTA1Mjc1NjcvMzM5MzMwNzk2LTQwNTkxMTYxLWI1MjItNGZiMS1iZGRmLWUyYmI2MTdmODY0Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QxNDI0MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZWViNjg3YWQ3ZjMzMGViYWNjOGZkY2I4N2Q4MDc3ODAyODFmYWY1YzUxZTYzYjc4MzRjNTc0NDAwOGRkZGVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9TnwnXg8C4G97t9bbqRJb_xt2rp2QltTwE00n-xBxnI)
> 
> I am not getting this error. Pls retest and if still getting the error, provide more detail on the steps to reproduce.

Alex, today I got the same error when using the link sent in Discord.
https://dev.app.spiff.status.im/i/534
![image](https://github.com/sartography/spiff-arena/assets/110527567/9ab77bf8-fac6-4071-8a88-d8d351c48f16)

Please try with these info
Issue No : 1320, git : madhurrya discord : madhurya1 (I'll send you the link when I get it)
![image](https://github.com/sartography/spiff-arena/assets/110527567/56ae5fdc-b43b-4c1b-b2ea-d5b3298e4411)

**Comment by madhurrya** [comment]
> > 23. When I submit/resubmit it shows this loading screen for a long time. It might be better to show some text here. Otherwise user might feel something is wrong.
> >     ![image](https://private-user-images.githubusercontent.com/110527567/339330300-f79f3223-39de-4d16-b047-cda0a9fe3269.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyODg5NDksIm5iZiI6MTcxODI4ODY0OSwicGF0aCI6Ii8xMTA1Mjc1NjcvMzM5MzMwMzAwLWY3OWYzMjIzLTM5ZGUtNGQxNi1iMDQ3LWNkYTBhOWZlMzI2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QxNDI0MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Y2VmNmY5NWNjZTg5MTU0ZmMwZmI4ZjM5Y2Q3MGMyOWUwN2VmYjY0ZmVkMGRmYTRmN2UyYzEwYWYwYmZjMTg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wDzvPHc3iqCoCvgZ9pgiTnf70UOBmAsxcktbTgykRq4)
> 
> @madhurrya or @dinithihj I added some text to display after the initial submission and it is not showing up. I suspect that this feature is not working on the interstitial page when transitioning between Guest User Forms, but not sure. If you haven't already, would you please set up a test process to confirm/refute that this is the issue and if it is, write up an issue for it.

I added an issue for this https://github.com/sartography/spiff-arena/issues/1740

**Comment by madhurrya** [comment]
> > 25. When I click the Home button here it shows the Spiff home page for few seconds and then it says Access denied. Please check this videos. https://drive.google.com/file/d/19Oq9wqR4TXJxYwR99gv6RnFtDX7x6zQl/view?usp=sharing
> > 
> > ![image](https://private-user-images.githubusercontent.com/110527567/339331561-a593ec27-c66f-4073-9278-f9416b0bc375.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyODg5NDksIm5iZiI6MTcxODI4ODY0OSwicGF0aCI6Ii8xMTA1Mjc1NjcvMzM5MzMxNTYxLWE1OTNlYzI3LWM2NmYtNDA3My05Mjc4LWY5NDE2YjBiYzM3NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QxNDI0MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NGRjOWVkNTVlZmM3YjUwMmNkMTFjOWNhMGMxODgzMTUyMzBhM2EzNzc0ZTg4MjlkNWEyYTVmYjg5NGJjYjc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CrAqMdVVSZjButiHbM-z7fIV6ga4wraitcJ8jj48iIo)
> 
> @madhurrya I suspect this issue here is we shouldn't take a Guest user to the Home page since they don't have the rights to do anything there. If @burnettk and/or @jasquat concur, please write up an issue so we can address this.

Added an Issue for this https://github.com/sartography/spiff-arena/issues/1741

**Comment by calexh-sar** [comment]
> > 27. [@harmeet-status](https://github.com/harmeet-status) is there any security risk in sending both the url and the password at the same time to the same place?
> >     ![image](https://private-user-images.githubusercontent.com/110527567/339333372-9a26643d-b7a8-4df3-a6fb-c9b69da9a39c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNzg3NzcsIm5iZiI6MTcxODI3ODQ3NywicGF0aCI6Ii8xMTA1Mjc1NjcvMzM5MzMzMzcyLTlhMjY2NDNkLWI3YTgtNGRmMy1hNmZiLWM5YjY5ZGE5YTM5Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QxMTM0MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NzViNmNmOWJiMmNlY2NjMjRmOGEyYzBlMWI5MjE5ZmJhYjcxNDliZjBiZWExNTg5OWY1MWY3MGFlZTRjZTVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1VrscMrAK3i1OLx5SaoddR55KUF053NMJwCBUV_Kx48)
> 
> This is ok, run past security. I'm actually considering just sending 1 message, with the secret in the URL. All websites when they get you to confirm the email belongs to you, send you just 1 link to verify. We can follow the same practise, since we no longer allow the user to retrieve an already filled out request, the need to have 2 separate messages, 1 including the link and the other including the password is no longer required.
> 
> [@calexh-sar](https://github.com/calexh-sar) could you pls update the model to just use the GUID and not required a password

Done

**Comment by calexh-sar** [comment]
@madhurrya regarding #24, the primary reason you were getting this error is because #1320 is a PR, not an issue.  In production this should have been caught by the label check since I don't know of any reason a PR would be assigned one of the Bounty labels.  But to be safe and thorough, I added a check to make sure the issue requested was a PR with an incorrectly placed bounty label.

**Comment by harmeet-status** [comment]
Hi EVERYONE, this thread is getting really busy so if any bugs or improvement are raised and they have been fixed/implemented, then pls go back and -mark with strikethrough-.

**Comment by madhurrya** [comment]
@harmeet-status is it OK if we create a new ticket for any new issues we find?

**Comment by harmeet-status** [comment]
28. Got this error after I tried to submit a request, but my GitHub account name was wrong. So then I started again and getting this error. I didn't clear cookies or close browser, I did try to close tab and re-open but getting this error still.

![Image](https://github.com/sartography/spiff-arena/assets/104047049/885fc985-b89a-4bba-90b7-99a5c14bc270)

**Comment by madhurrya** [comment]
New issues will be added in this ticket https://github.com/sartography/spiff-arena/issues/1752
